### ISSUE TITLE
multi-user use case, trying to avoid "token sharing"

### ISSUE THREAD

**Issue by insatomcat** [markhoerth/dremio_client#56]
I'm trying to use dremio_client in an existing django app, where dremio_client must act with the connected user's privilege level. 
It mean that if an admin and a non admin user are using the app at the same time, dremio_client must use the admin privilege on dremio with the admin user and the non-admin privilege with the non-admin user.
The authentication in dremio is passed either throught a yaml file (seems inapropriate in this use case) or throught environment variables (which seems more appropriate).
Howerver if I use environment variables I'm not quite sure I understand how dremio_client will manage the "session" (will it store and reuse of the token in a file with the use of the _existing_token method, or if not reauth for each and every request?)
it seems either there's a risk the token will be shared amongst user, or that it will suffer performance problem by reauthenticating at every request. Since this webapp is there to launch batch processing on thousands of VDS, I'm concerned.

Maybe we could add a possibility to init the client with a preexisting token ? I'm willing to work on it but I don't understand the codebase enough to be sure that's the best way to solve my issue.
Let me add that I'm a django total beginner.

Could you share your thoughts on this please ?
Thanks.

**Comment by rymurr** [comment]
Hey @insatomcat 

I have done the following in the case of multiple Dremio environments for the same user:

The dremio client takes a config path as an argument so I set up a directory for each environment and put the relevant yaml config there. Depending on which environment I want to work with I pass the relevant directory into the client at construction. 

The client also writes an `auth.json` file into the config directory saving the current token. On construction the client checks if the token is still valid and uses it rather than re-authenticating.  If the token has expired we will have to re-auth.

Note the `init` method also takes a `config_dict` argument in which you can add parameters without setting env variables (eg `{'auth.password': 'foobar'}`).

I would probably use the config dir model for everything but your passwords and let the client store the auth tokens in that directory as well. The passwords I would likely store in a more secure way and pass in via the `dict` method. Make sense?

If you are inclined to pass the token directly the `conf` and `auth` modules are the places to look. I am not 100% convinced that exposing the token is the way to go. Part of the original design was to hide as much as possible of the internal workings of Dremio's REST api from the user.

**Comment by insatomcat** [comment]
Thank you for your answer. I understand your willingness to hide the internals, but it's a tradeoff which then requires to write the token on disk and so makes the config dir model inevitable.
As I would prefer to stay in memory, couldn't the token be stored somewhere in the client object, instead of on disk ?
